In [1]:
import torch

x = torch.tensor([3.5])
y = torch.tensor([2.0])

x+y,x-y,x*y,x/y,x**y

(tensor([5.5000]),
 tensor([1.5000]),
 tensor([7.]),
 tensor([1.7500]),
 tensor([12.2500]))

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [4]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [7]:
x = torch.arange(20).reshape(5,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
x.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
b = torch.tensor([[1,2,3],
                 [2,4,5],
                 [3,5,6]])
b == b.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [14]:
a = torch.arange(20).reshape(5,4)
b = a.clone()
a,a+b

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]))

In [15]:
c = 2
a,a+c

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13],
         [14, 15, 16, 17],
         [18, 19, 20, 21]]))

In [16]:
a,a.sum()

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor(190))

In [18]:
a = torch.arange(20*2).reshape(2,5,4)
a.shape,a.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [19]:
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [23]:
a_sum_axis0 = a.sum(axis = 0)
a_sum_axis0,a_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [25]:
a_sum_axis1 = a.sum(axis = 1)
a_sum_axis1,a_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [28]:
a.sum(axis=[0,1]).shape

torch.Size([4])

In [30]:
a.sum()/a.numel()

tensor(19.5000)

In [31]:
a.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long